frontend/api/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'queryapi', views.QueryInfoViewSet, basename='queryapi')

urlpatterns =[
	path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

  ]

frontend/app/urls.py
from django.urls import path
from django.conf.urls import include
from rest_framework import routers
from . import views

app_name = 'app'

urlpatterns =[
	path('search/',views.search,name='search'),

]

frontend/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('api/',include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/api/models.py
from django.db import models

# Create your models here.

frontend/app/models.py
from django.db import models

class QueryInfo(models.Model):
	query = models.CharField(max_length=200)
	url = models.CharField(max_length=500,null=True,blank=True)
	query_date = models.DateTimeField(auto_now_add=True)
	processed_count = models.IntegerField(default=0)
	mark = models.BooleanField(default=False)

	class Meta:
		db_table = 'query_info'
		verbose_name_plural='Query Info'

	def __str__(self):
		return self.query

frontend/api/views.py
from rest_framework import viewsets
from app.models import QueryInfo
from .serializers import *
from django.db.models import Q
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404


class QueryInfoViewSet(viewsets.ModelViewSet):
	serializer_class = QueryInfoSerializer
	# queryset = QueryInfo.objects.all() 

	def get_queryset(self):
		query = self.request.query_params.get('query')
		if query:
			return QueryInfo.objects.filter(Q(query__icontains=query) & Q(mark = 1))
			# serializer = QueryInfoSerializer(queryset, many=True)
			# return Response(serializer.data)
		return QueryInfo.objects.all()

	def create(self, request, *args, **kwargs):
		is_many = isinstance(request.data, list)
		if not is_many:
			return super(QueryInfoViewSet, self).create(request, *args, **kwargs)
		else:
			serializer = self.get_serializer(data=request.data, many=True)
			serializer.is_valid(raise_exception=True)
			self.perform_create(serializer)
			headers = self.get_success_headers(serializer.data)
			return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

	def destroy(self, request, *args, **kwargs):
		try:
			instance = self.get_object()
			self.perform_destroy(instance)
		except Http404:
			pass
		return Response({"msg":"Deleted successfully",
						"status":status.HTTP_200_OK}
						)

	def update(self, request, *args, **kwargs):
		instance = self.get_object()
		serializer = self.get_serializer(instance, data=request.data)
		serializer.is_valid(raise_exception=True)
		self.perform_update(serializer)
		return Response(serializer.data)

frontend/app/views.py
from django.shortcuts import render
from .models import *
import requests

def search(request):
	
	if request.method == 'POST':
		query = request.POST.get('search')
		# print(query)
		# resp = requests.get("http://127.0.0.1:8000/api/queryapi/?query={}".format(query))
		# data = resp.json()
		# print(data)
		res = QueryInfo.objects.filter(query__icontains=query)
		# print(res)
		if query:
			return render(request,'google_sec.html',{'data':res,'query':query})
		else:
			return render(request,'search-eng.html')
	return render(request,'search-eng.html')

frontend/app/templates/google_sec.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>google</title>

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- style-link -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- bootstrap link -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!-- font-awesome -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<body>

	<!-- top-sec -->

	<header class="google_header">
		<div class="container-fluid">
		<div class="logo-sec">
			<img src="" alt="Image"/>
		</div>
		<div class="header_input">
      <form action = "{% url 'app:search' %}" method="post"> 
      {% csrf_token %}
			 <input type="text" name="search" value="{{ query }}">
       <button type="submit" class="search_btn" style="border: none ; position: absolute; top: 6px; right: 10px;"><i class="fa fa-search" aria-hidden="true"></i></button>
      </form>
			<a href="" class="google_mic"><img src="{% static 'images/mic.png' %}"/></a>
		</div>
		<div class="google_apps">
			<ul>
				<li class="google_apps_dots">
					<i class="fa fa-bars" aria-hidden="true"></i>
				</li>
				<li class="email_id_sec">
					<span>J</span>
				</li>
			</ul>
		</div>
		</div>
	</header>


<section class="section_part">

		<div class="tabs_main">

<ul class="nav google_navslocal" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link tabs_heading active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><i class="fa fa-search" aria-hidden="true"></i> All</a>
  </li>
  <li class="nav-item">
    <a class="nav-link tabs_heading" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fa fa-picture-o" aria-hidden="true"></i> Images</a>
  </li>
  <li class="nav-item">
    <a class="nav-link tabs_heading" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"><i class="fa fa-play-circle" aria-hidden="true"></i> Vedios</a>
  </li>
  <li class="nav-item">
    <a class="nav-link tabs_heading" id="contact-tab" data-toggle="tab" href="#News" role="tab" aria-controls="News" aria-selected="false"> <i class="fa fa-newspaper-o" aria-hidden="true"></i> News</a>
  </li>
  <li class="nav-item">
    <a class="nav-link tabs_heading" id="contact-tab" data-toggle="tab" href="#Shopping" role="tab" aria-controls="Shopping" aria-selected="false">Shopping</a>
  </li>
</ul>

<hr style="width: 100%; height: 1px;margin: 3px 0;">

<div class="tab-content  googletab_cntnt" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
  	
    {% for d in data %}

      <a href = "{{ d.url }}"> {{ d.url }} </a> <br><br>

    {% endfor %}


  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
Why do we use it?
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search

  </div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
Where does it come from?
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites

  </div>
  <div class="tab-pane fade" id="News" role="tabpanel" aria-labelledby="News-tab">
  	
Where can I get some?
There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet

  </div>
  <div class="tab-pane fade" id="Shopping" role="tabpanel" aria-labelledby="Shopping-tab">
  	
"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business

  </div>
</div>

</div>
</section>




<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<!-- bootstrap script -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>



</body>
</html>

frontend/app/templates/search-eng.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>google</title>

	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- style-link -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- bootstrap link -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!-- font-awesome -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<body>

	<section class="main_sec">
		<div class="google-icon">
			<img src="" alt="img"/>
		</div>
		<div class="google_searchicon">
		<form action = "{% url 'app:search' %}" method="post"> 
			{% csrf_token %}
			<input type="text" placeholder="Search Google or type a URL" name="search">
		</form>
			<a href=""><img src="{% static 'images/mic.png' %}"/></a>
		</div>

		<div class="google_shortcut_icons">
			<ul>
				<li>
					<div class="shorcut_main">
						<div class="shorcut_img">
							<img src="{% static 'images/gmail.png' %}"/>
						</div>
						<div class="shorcut_p">
							<p>Inbox</p>
						</div>
					</div>
				</li>
				<li>
					<div class="shorcut_main">
						<div class="shorcut_img">
							<img src="{% static 'images/linkedin.png' %}"/>
						</div>
						<div class="shorcut_p">
							<p>Linkedin</p>
						</div>
					</div>
				</li>
				<li>
					<div class="shorcut_main">
						<div class="shorcut_img">
							<img src="{% static 'images/skype.png' %}"/>
						</div>
						<div class="shorcut_p">
							<p>Skype</p>
						</div>
					</div>
				</li>
				<li>
					<div class="shorcut_main">
						<div class="shorcut_img">
							<img src="{% static 'images/whatsapp.png' %}"/>
						</div>
						<div class="shorcut_p">
							<p>WhatsApp</p>
						</div>
					</div>
				</li>
			</ul>
		</div>
	</section>

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<!-- bootstrap script -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>